// Generated by CoffeeScript 1.8.0
(function() {
  var __slice = [].slice;

  define(function() {
    var rgb, rgba;
    rgb = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return "rgb(" + (args.join(", ")) + ")";
    };
    rgba = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return "rgba(" + (args.join(", ")) + ")";
    };
    return {
      rgb: rgb,
      rgba: rgba,
      red: rgb(200, 0, 0),
      green: rgb(0, 200, 0),
      blueTint: rgba(0, 0, 200, 0.5),
      black: rgb(0, 0, 0)
    };
  });

}).call(this);

//# sourceMappingURL=color.map
