// Generated by CoffeeScript 1.8.0
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(["onload", "keys"], function(onload, KEYS) {
    var addKey, keysThatAreDown, removeKey;
    keysThatAreDown = [];
    addKey = function(key) {
      if (__indexOf.call(keysThatAreDown, key) >= 0) {
        return;
      }
      return keysThatAreDown.push(key);
    };
    removeKey = function(key) {
      var i;
      if (__indexOf.call(keysThatAreDown, key) < 0) {
        return;
      }
      i = keysThatAreDown.indexOf(key);
      keysThatAreDown.splice(i, 1);
      return removeKey(key);
    };
    onload(function() {
      addEventListener("keydown", function(e) {
        return addKey(e.which);
      });
      return addEventListener("keyup", function(e) {
        return removeKey(e.which);
      });
    });
    return {
      isDown: function(key) {
        var _ref;
        if (!(key in KEYS)) {
          console.warn("Unknown Key: " + key);
        }
        return _ref = KEYS[key], __indexOf.call(keysThatAreDown, _ref) >= 0;
      },
      getKeys: function() {
        var key, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = keysThatAreDown.length; _i < _len; _i++) {
          key = keysThatAreDown[_i];
          _results.push(KEYS[key]);
        }
        return _results;
      },
      getCodes: function() {
        return keysThatAreDown.slice(0);
      }
    };
  });

}).call(this);

//# sourceMappingURL=input.map
