// Generated by CoffeeScript 1.8.0
(function() {
  var KEYS, code, key, _i, _j, _ref, _ref1, _ref2, _ref3;

  KEYS = {
    'Left Arrow': 37,
    'Up Arrow': 38,
    'Right Arrow': 39,
    'Down Arrow': 40,
    'Space': 32
  };

  for (code = _i = _ref = 'A'.charCodeAt(0), _ref1 = 'Z'.charCodeAt(0); _ref <= _ref1 ? _i <= _ref1 : _i >= _ref1; code = _ref <= _ref1 ? ++_i : --_i) {
    key = String.fromCharCode(code);
    KEYS[key] = code;
  }

  for (code = _j = _ref2 = '0'.charCodeAt(0), _ref3 = '9'.charCodeAt(0); _ref2 <= _ref3 ? _j <= _ref3 : _j >= _ref3; code = _ref2 <= _ref3 ? ++_j : --_j) {
    key = String.fromCharCode(code);
    KEYS[key] = code;
  }

  for (key in KEYS) {
    code = KEYS[key];
    KEYS[code] = key;
  }

  define(KEYS);


  /*
  Others I might want later
         8      Backspace
         9      Tab
        13      Enter
        16      Shift
        17      Ctrl
        18      Alt
        19      Pause, Break
        20      CapsLock
        27      Esc
        32      Space
        33      Page Up
        34      Page Down
        35      End
        36      Home
        37      Left arrow
        38      Up arrow
        39      Right arrow
        40      Down arrow
        44      PrntScrn (see below†)
        45      Insert
        46      Delete
       144      NumLock
       145      ScrollLock
       188      , <
       190      . >
       191      / ?
       192      ` ~
       219      [ { (see below‡)
       220      \ |
       221      ] }
       222      ' "
   */

}).call(this);

//# sourceMappingURL=keys.map
