// Generated by CoffeeScript 1.8.0
(function() {
  var reqs;

  reqs = ["onLoad", "world", "display", "input"];

  require(reqs, function(onLoad, world, display, input) {
    var constants, init, run, state;
    constants = {
      interval: 1000 / 60
    };
    state = {
      running: false,
      canvas: null,
      startTime: +new Date(),
      lastFrame: +new Date(),
      timeElapsed: 0
    };
    init = function() {
      state.width = 960;
      state.height = 540;
      state.running = true;
      display.init(state);
      display.showFPS = false;
      state.keys = input;
      return run();
    };
    run = function() {
      state.startElapsed = +new Date() - state.startTime;
      state.frameElapsed = +new Date() - state.lastFrame;
      if (state.running) {
        world.update(state);
        world.render(state, display);
      }
      setTimeout(run, constants.interval);
      return state.lastFrame = +new Date();
    };
    return onLoad(init);
  });

}).call(this);

//# sourceMappingURL=main.map
