// Generated by CoffeeScript 1.8.0
(function() {
  define(function() {
    var loadComplete, postponedFuncs;
    postponedFuncs = [];
    loadComplete = document.readystate !== "loading";
    if (!loadComplete) {
      document.addEventListener("readystatechange", function() {
        var f, _i, _len, _results;
        loadComplete = true;
        _results = [];
        for (_i = 0, _len = postponedFuncs.length; _i < _len; _i++) {
          f = postponedFuncs[_i];
          _results.push(f());
        }
        return _results;
      });
    }
    return function(func) {
      if (loadComplete) {
        func();
      } else {
        postponedFuncs.push(func);
      }
    };
  });

}).call(this);

//# sourceMappingURL=onload.map
