// Generated by CoffeeScript 1.8.0
(function() {
  define(["actors"], function(actors) {
    return {
      update: function(state) {
        var actor, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = actors.length; _i < _len; _i++) {
          actor = actors[_i];
          _results.push(actor.update(state));
        }
        return _results;
      },
      render: function(state, display) {
        var actor, target, targets, _ref;
        targets = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = actors.length; _i < _len; _i++) {
            actor = actors[_i];
            _results.push((function() {
              var _j, _len1, _ref, _results1;
              _ref = actor.getRenderTargets();
              _results1 = [];
              for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
                target = _ref[_j];
                _results1.push(target);
              }
              return _results1;
            })());
          }
          return _results;
        })();
        targets = (_ref = []).concat.apply(_ref, targets);
        return display.renderWorld(state, targets);
      }
    };
  });

}).call(this);

//# sourceMappingURL=world.map
